'use strict';
const $=id=>document.getElementById(id), symbols=['SPY','QQQ','AGG','GLD','CASH'];
const labels=['US large-cap stocks','Nasdaq 100 / technology tilt','US aggregate bonds','Gold','Uninvested · 0% interest'];
let result=null,busy=false;
let token=localStorage.getItem('mtm-token');if(!token){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');localStorage.setItem('mtm-token',token);}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n), pct=n=>n.toFixed(2)+'%';
async function api(path,body){const response=await fetch((window.MARKET_API_BASE||'')+'/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Experiment-Token':token},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(90000)});let data;try{data=await response.json();}catch{throw new Error('The Python backend is unavailable. Start backend/app.py; a static preview alone cannot run simulations.');}if(!response.ok)throw new Error(data.error||'Request failed');return data;}
function status(text){$('status').textContent=text;}
symbols.forEach((s,i)=>{const row=document.createElement('div');row.className='weight';const label=document.createElement('label');label.htmlFor='w'+s;label.textContent=s;const small=document.createElement('small');small.textContent=labels[i];label.append(small);const input=document.createElement('input');Object.assign(input,{id:'w'+s,type:'number',min:'0',max:'100',step:'1',value:[40,20,30,10,0][i]});input.addEventListener('input',()=>{$('total').textContent=symbols.reduce((n,k)=>n+Number($('w'+k).value),0)+'%';});row.append(label,input);$('weights').append(row);});
function config(){return {start:$('start').value,end:$('end').value,initial:Number($('initial').value),contribution:Number($('contribution').value),fee:Number($('fee').value),rule:$('rule').value,weights:Object.fromEntries(symbols.map(s=>[s,Number($('w'+s).value)]))};}
function apply(c){['start','end','initial','contribution','fee','rule'].forEach(k=>$(k).value=c[k]);symbols.forEach(s=>$('w'+s).value=c.weights[s]);$('total').textContent='100%';}
async function run(){if(busy)return;busy=true;$('run').disabled=true;status('Running strategy, benchmark, and historical-window tests…');try{result=await api('simulate',config());render();status('Experiment complete. Change a rule or inspect a month below.');}catch(e){status(e.message);}finally{busy=false;$('run').disabled=false;}}
$('setup').addEventListener('submit',e=>{e.preventDefault();run();});
function render(){ $('empty').hidden=true;$('output').hidden=false;const m=result.runs.strategy.metrics;$('stats').replaceChildren();[['Final balance',money(m.final)],['Net gain after deposits',money(m.gain)],['Annualized return',pct(m.annualReturn)],['Maximum drawdown',pct(m.drawdown)],['Monthly-return volatility',pct(m.volatility)],['Total deposits',money(m.invested)],['Trading costs',money(m.fees)],['Rebalances',String(result.runs.strategy.trades.length-1)]].forEach(([label,value])=>{const d=document.createElement('div');d.className='stat';const v=document.createElement('strong');v.textContent=value;const l=document.createElement('span');l.textContent=label;d.append(v,l);$('stats').append(d);});$('scrub').max=result.runs.strategy.points.length-1;$('scrub').value=$('scrub').max;chart();$('rolling').replaceChildren();result.rolling.forEach(r=>{const d=document.createElement('div');d.className='window';[r.start+' → '+r.end,'Strategy '+pct(r.strategy),'SPY '+pct(r.benchmark)].forEach(v=>{const s=document.createElement('span');s.textContent=v;d.append(s);});$('rolling').append(d);});$('tradeCount').textContent=result.runs.strategy.trades.length+' allocation events · open ledger';$('trades').replaceChildren();result.runs.strategy.trades.forEach(t=>{const tr=document.createElement('tr');[t.date,t.reason,Object.entries(t.trades).map(([s,v])=>s+' '+(v>=0?'+':'−')+money(Math.abs(v))).join(' · '),money(t.cost)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});$('trades').append(tr);});}
function chart(){if(!result)return;const svg=$('chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();const metric=$('view').value,runs=Object.values(result.runs),all=runs.flatMap(r=>r.points.map(p=>p[metric]));let low=Math.min(...all),high=Math.max(...all);if(low===high){low-=1;high+=1;}const x=i=>65+i/(runs[0].points.length-1)*710,y=v=>285-(v-low)/(high-low)*250;function node(tag,attrs,text){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.append(n);return n;}for(let i=0;i<5;i++){const v=low+(high-low)*i/4;node('line',{x1:65,x2:775,y1:y(v),y2:y(v),stroke:'var(--line)'});node('text',{x:0,y:y(v)+4},metric==='value'?money(v):pct(v));}runs.forEach((r,i)=>node('path',{d:r.points.map((p,j)=>(j?'L':'M')+x(j)+','+y(p[metric])).join(' '),fill:'none',stroke:['var(--gold)','var(--blue)','var(--muted)'][i],'stroke-width':i===0?3:1.7}));const points=runs[0].points;node('text',{x:65,y:320},points[0].date);node('text',{x:710,y:320},points.at(-1).date);const idx=Number($('scrub').value);node('line',{x1:x(idx),x2:x(idx),y1:25,y2:285,stroke:'var(--ink)','stroke-dasharray':'3 5'});$('inspect').textContent=points[idx].date+' / '+Object.entries(result.runs).map(([k,r])=>k+': '+(metric==='value'?money(r.points[idx].value):pct(r.points[idx].drawdown))).join(' · ');}
$('view').addEventListener('change',chart);$('scrub').addEventListener('input',chart);$('theme').onclick=()=>document.body.classList.toggle('light');
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const weights={balanced:[60,0,40,0,0],tech:[30,60,0,0,10],diverse:[40,20,30,10,0]}[b.dataset.preset];symbols.forEach((s,i)=>$('w'+s).value=weights[i]);$('total').textContent='100%';});
async function saved(){const d=await api('experiments');$('saved').replaceChildren();if(!d.experiments.length)$('saved').textContent='No experiments saved yet.';d.experiments.forEach(e=>{const b=document.createElement('button');b.textContent=e.name+' · '+e.config.start;b.onclick=()=>{apply(e.config);run();};$('saved').append(b);});}
$('save').onclick=async()=>{if(!result)return;$('save').disabled=true;try{await api('experiments',{name:$('name').value,config:result.config});await saved();status('Saved. Select its name to rerun the experiment.');}catch(e){status(e.message);}finally{$('save').disabled=false;}};
$('export').onclick=()=>{if(!result)return;const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='market-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
(async()=>{try{const d=await api('market');for(const id of ['start','end'])d.dates.forEach(date=>{const o=document.createElement('option');o.value=o.textContent=date;$(id).append(o);});$('start').value=d.dates.includes('2015-01')?'2015-01':d.dates[0];$('end').value=d.dates.at(-1);$('source').textContent=d.source.provider+' · Retrieved '+d.source.retrieved.slice(0,10)+' · '+d.dates[0]+' to '+d.dates.at(-1)+' · Cached snapshot';await saved();status('Historical data ready. Design your strategy, then run it.');}catch(e){status('Could not connect. Run python3 backend/app.py and open http://127.0.0.1:8766/. '+e.message);$('run').disabled=true;}})();
