'use strict';
let paperReport=null,paperBusy=false;
const preciseMoney=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
function paperMessage(t){$('paperStatus').textContent=t;}
function paperSettings(){const c=config();$('paperSetup').textContent=money(c.initial)+' · '+symbols.map(s=>s+' '+c.weights[s]+'%').join(' / ')+' · '+c.fee+' bps fee';}
$('setup').addEventListener('input',paperSettings);document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',paperSettings));paperSettings();
async function paperList(selected){const d=await api('paper');$('paperSelect').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Select a portfolio';$('paperSelect').append(placeholder);d.portfolios.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+p.created.slice(0,10);$('paperSelect').append(o);});if(selected)$('paperSelect').value=selected;}
function paperButtons(disabled){paperBusy=disabled;['paperCreate','paperRefresh','paperSelect'].forEach(id=>$(id).disabled=disabled);}
async function paperValue(id){paperReport=await api('paper/value',{id});renderPaper();paperMessage('Valuation recorded. Refresh later to observe changes; holdings stay fixed.');}
$('paperCreate').onclick=async()=>{if(paperBusy)return;paperButtons(true);paperMessage('Requesting current prices and creating pretend holdings…');try{const c=config();const p=await api('paper',{name:$('paperName').value,initial:c.initial,weights:c.weights,fee:c.fee});await paperList(p.id);await paperValue(p.id);}catch(e){paperMessage(e.message);}finally{paperButtons(false);}};
async function paperRefresh(){const id=$('paperSelect').value;if(!id){paperMessage('Select a saved paper portfolio first.');return;}if(paperBusy)return;paperButtons(true);paperMessage('Checking the latest available prices…');try{await paperValue(id);}catch(e){paperMessage(e.message+' Previous results below are unchanged.');}finally{paperButtons(false);}}
$('paperRefresh').onclick=paperRefresh;$('paperSelect').onchange=()=>{paperReport=null;$('paperOutput').hidden=true;$('paperEmpty').hidden=false;paperRefresh();};
function renderPaper(){const r=paperReport,v=r.valuation;$('paperEmpty').hidden=true;$('paperOutput').hidden=false;$('paperTitle').textContent=r.name+' · Opened '+new Date(r.openedAt).toLocaleString();$('paperStats').replaceChildren();[['Current value',preciseMoney(v.total)],['Gain after opening costs',preciseMoney(v.gain)],['Change since funding',pct(v.gainPercent)],['Largest allocation drift',v.maxDrift.toFixed(2)+' pts'],['Opening trading cost',preciseMoney(v.openingCost)],['Observed snapshots',r.history.length]].forEach(([label,value])=>{const d=document.createElement('div');d.className='stat';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;d.append(strong,span);$('paperStats').append(d);});const stale=Object.values(v.market.quotes).some(q=>q.stale);$('paperSource').textContent='Fintable · Retrieved '+new Date(v.market.fetchedAt).toLocaleString()+(v.market.cached?' · Server cache':' · Fresh provider request')+(stale?' · Warning: at least one quote is over 96 hours old.':'')+' · Feed prices may be delayed.';$('paperRows').replaceChildren();v.rows.forEach(row=>{const tr=document.createElement('tr'),quote=v.market.quotes[row.symbol];[row.symbol,row.shares==null?'—':row.shares.toFixed(4),quote?preciseMoney(quote.price)+' / '+new Date(quote.asOf).toLocaleString()+' ('+quote.feed+')':'—',preciseMoney(row.value),pct(row.target)+' / '+pct(row.actual),(row.drift>=0?'+':'')+row.drift.toFixed(2)+' pts'].forEach(text=>{const td=document.createElement('td');td.textContent=text;tr.append(td);});$('paperRows').append(tr);});$('paperPlan').replaceChildren();v.plan.trades.forEach(t=>{const span=document.createElement('span');span.textContent=t.symbol+': '+(t.dollars>=0?'buy ':'sell ')+preciseMoney(Math.abs(t.dollars))+' ('+Math.abs(t.shares).toFixed(4)+' shares)';$('paperPlan').append(span);});$('paperCost').textContent='Estimated costs: '+preciseMoney(v.plan.cost)+' · Cash after: '+preciseMoney(v.plan.cashAfter)+' · Portfolio after costs: '+preciseMoney(v.plan.valueAfter);paperChart();}
function paperChart(){const history=paperReport.history,svg=$('paperChart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();const values=history.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),margin=Math.max((max-min)*.1,max*.001,1),low=min-margin,high=max+margin;const x=i=>70+(history.length===1?0:i/(history.length-1)*600),y=v=>170-(v-low)/(high-low)*140;function node(tag,attrs,text){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.append(n);}for(let i=0;i<3;i++){const v=low+(high-low)*i/2;node('line',{x1:70,x2:670,y1:y(v),y2:y(v),stroke:'var(--line)'});node('text',{x:0,y:y(v)+4},money(v));}node('path',{d:history.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.value)).join(' '),fill:'none',stroke:'var(--gold)','stroke-width':2});history.forEach((p,i)=>node('circle',{cx:x(i),cy:y(p.value),r:3,fill:'var(--gold)'}));node('text',{x:70,y:205},new Date(history[0].date).toLocaleDateString());$('paperHistory').textContent=history.length===1?'One observation so far. Return after prices change to build a history.':'First: '+new Date(history[0].date).toLocaleString()+' · Last: '+new Date(history.at(-1).date).toLocaleString();}
$('paperDownload').onclick=()=>{if(!paperReport)return;const url=URL.createObjectURL(new Blob([JSON.stringify(paperReport,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='paper-portfolio.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
(async()=>{try{await paperList();paperMessage('Ready. Start a paper portfolio or open a saved one.');}catch(e){paperMessage(e.message);}})();
